baseURL = "https://kgaurav.online/"
languageCode = "en-us"
title = "Kumar Gaurav, Software Engineer"
theme = "cactus"

[params]
  colortheme = "dark" # dark, light, white, or classic
  description = "I create things to empower free learning & OSS. I'm learning about Earthship and Permaculture these days, possibbly to create a sustainable co-operative living. I will be glad to know if we can work together."
  mainSection = ""
  tagsOverview = false
  showProjectsList = false

# Main menu which appears below site header.
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[params.social]]
  name = "github"
  link = "https://github.com/mrdotkg/"

[[params.social]]
  name = "linkedin"
  link = "https://www.linkedin.com/in/mrdotkg/"

[[params.social]]
  name = "twitter"
  link = "https://twitter.com/mrdotkg/"

[[params.social]]
  name = "email"
  link = "kgaurav@butterops.dev" # no need for "mailto:" at the start
